// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVS7wFGmdvmY4fcMwvt3WWNATKD4RWiw',
    appId: '1:902207302809:web:7328bd3e139448b39a1c08',
    messagingSenderId: '902207302809',
    projectId: 'milicheck-8f445',
    authDomain: 'milicheck-8f445.firebaseapp.com',
    storageBucket: 'milicheck-8f445.firebasestorage.app',
    measurementId: 'G-EY44ZQENH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWkWdXR97FsbYi93mwUIdxaZjkdpas7nM',
    appId: '1:902207302809:android:ab431f80683127f89a1c08',
    messagingSenderId: '902207302809',
    projectId: 'milicheck-8f445',
    storageBucket: 'milicheck-8f445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRO5BAYRg1-TjjUr5zmnbSVN64eEmA_FA',
    appId: '1:902207302809:ios:54319794ab8fc98f9a1c08',
    messagingSenderId: '902207302809',
    projectId: 'milicheck-8f445',
    storageBucket: 'milicheck-8f445.firebasestorage.app',
    iosBundleId: 'com.example.milicheck',
  );
}
